# Meet the SWAMP Team!

The SWAMP Team is composed of multiple team members at the State Water Board within the SWAMP Unit, SWAMP Information Management and Quality Assurance Center (SWAMP IQ), and others in the Office of Information Management and Analysis (OIMA).

## SWAMP Unit

+-------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------+
| Name                                                              | Title                                                 | Program Area(s)                                                                            |
+===================================================================+=======================================================+============================================================================================+
| Ali Dunn                                                          | Senior Environmental Scientist, Supervisor, Unit Lead | SWAMP Coordinator of statewide monitoring programs, plans and budgets                      |
+-------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------+
| Leah Benton                                                       | CivicSpark Fellow                                     | Tribal Data Initiatives                                                                    |
+-------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------+
| Anna Holder                                                       | Environmental Scientist                               | SWAMP Statewide Bioaccumulation Program Coordinator                                        |
|                                                                   |                                                       |                                                                                            |
|                                                                   |                                                       | Data science, data visualization and programming (R \[preferred\], Python, Unix, SQL, GIS) |
|                                                                   |                                                       |                                                                                            |
|                                                                   |                                                       | Science communication                                                                      |
|                                                                   |                                                       |                                                                                            |
|                                                                   |                                                       | Openscapes                                                                                 |
|                                                                   |                                                       |                                                                                            |
|                                                                   |                                                       | Tribal Coordinator                                                                         |
|                                                                   |                                                       |                                                                                            |
|                                                                   |                                                       | Racial Equity Trainer                                                                      |
+-------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------+
| Mary Tappel                                                       | Environmental Scientist                               | Webpage updates                                                                            |
+-------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------+
| Michelle Tang                                                     | Environmental Scientist                               | Data science, data visualization and programming (JavaScript, Python)                      |
+-------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------+
| Shuka Rastegarpour                                                | Environmental Scientist                               | SWAMP Statewide Bioassessment Program Coordinator                                          |
+-------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------+
| [Sydney Rilum](https://caseagrant.ucsd.edu/profiles/sydney-rilum) | California Sea Grant Fellow                           | Data science, data visualization (R)                                                       |
|                                                                   |                                                       |                                                                                            |
|                                                                   |                                                       | Science communication                                                                      |
+-------------------------------------------------------------------+-------------------------------------------------------+--------------------------------------------------------------------------------------------+

## SWAMP IQ

+---------------------------+-------------------------------------------------------+---------------------------------------------------------+
| Name                      | Title                                                 | Program Area(s)                                         |
+===========================+=======================================================+=========================================================+
| Tessa Fojut               | Senior Environmental Scientist, Supervisor, Unit Lead | SWAMP Quality Assurance Officer                         |
|                           |                                                       |                                                         |
|                           |                                                       | Database Manager                                        |
+---------------------------+-------------------------------------------------------+---------------------------------------------------------+
| Candace Levesque          | Environmental Scientist                               | Bioassessment (algae) Data Manager                      |
+---------------------------+-------------------------------------------------------+---------------------------------------------------------+
| Cui (Scarlett) Li-Gherman | Scientific Aid                                        |                                                         |
+---------------------------+-------------------------------------------------------+---------------------------------------------------------+
| Delany Broome             | Environmental Scientist                               | Chemistry Data Manager                                  |
+---------------------------+-------------------------------------------------------+---------------------------------------------------------+
| Jennifer Salisbury        | Environmental Scientist                               | Tissue Data Manager                                     |
|                           |                                                       |                                                         |
|                           |                                                       | CEDEN Vocabulary Manager                                |
+---------------------------+-------------------------------------------------------+---------------------------------------------------------+
| Kimberly Pham             | Environmental Scientist                               | Chemistry Data Manager                                  |
+---------------------------+-------------------------------------------------------+---------------------------------------------------------+
| Lindsey Metz              | Environmental Scientist                               | Microbiology Data Manager                               |
|                           |                                                       |                                                         |
|                           |                                                       | Data science, data visualization and programming (R)    |
+---------------------------+-------------------------------------------------------+---------------------------------------------------------+
| Tony Gill                 | Environmental Scientist                               | Toxicity Data Manager                                   |
|                           |                                                       |                                                         |
|                           |                                                       | SPoT Program Coordinator                                |
+---------------------------+-------------------------------------------------------+---------------------------------------------------------+
| Toni Marshall             | Environmental Scientist                               | Bioassessment (benthic macroinvertebrates) Data Manager |
+---------------------------+-------------------------------------------------------+---------------------------------------------------------+

For more information, visit the [SWAMP IQ Wiki](https://sites.google.com/view/swamp-iq-wiki/swamp-iq-liaisons-and-data-managers)

## OIMA

+----------------+----------------------------------------+-----------------------------------------------------------------------------------------+
| Name           | Title                                  | Program Area(s)                                                                         |
+================+========================================+=========================================================================================+
| Carly Nilson   | Senior Environmental Scientist         | SWAMP Statewide Freshwater and Estuarine Harmful Algal Bloom (FHAB) Program Coordinator |
+----------------+----------------------------------------+-----------------------------------------------------------------------------------------+
| Chad Fearing   | Associate Governmental Program Analyst | Contracts                                                                               |
+----------------+----------------------------------------+-----------------------------------------------------------------------------------------+
| Devan Burke    | Associate Governmental Program Analyst | Contracts                                                                               |
|                |                                        |                                                                                         |
|                |                                        | Openscapes                                                                              |
|                |                                        |                                                                                         |
|                |                                        | Racial equity data projects and communication                                           |
+----------------+----------------------------------------+-----------------------------------------------------------------------------------------+
| Erick Burres   | Senior Environmental Scientist         | SWAMP Clean Water Team Coordinator                                                      |
+----------------+----------------------------------------+-----------------------------------------------------------------------------------------+
| Marisa VanDyke | Senior Environmental Scientist         | SWAMP Statewide Freshwater and Estuarine Harmful Algal Bloom (FHAB) Program Coordinator |
+----------------+----------------------------------------+-----------------------------------------------------------------------------------------+

## Former Fellows & Interns

+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Name                                                                                                | Title                       | Year      | Primary Project Area(s) & Products                                                                                                                                                                              |
+=====================================================================================================+=============================+===========+=================================================================================================================================================================================================================+
| Josh Davenport                                                                                      | Stanford Fellow             | 2023      | Tribal Data Initiatives                                                                                                                                                                                         |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | Tribal Water Data [Map](https://gispublic.waterboards.ca.gov/portal/home/item.html?id=a71c1841907240e1a4d896c8cf2302a8) & [User Manual](https://cawaterboarddatacenter.github.io/tribal-water-data-map-manual/) |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Badhia Yunes Katz](https://civicspark.civicwell.org/2022-23-fellows/entry/8887/)                   | CivicSpark Fellow           | 2022-2023 | Tribal Data Initiatives                                                                                                                                                                                         |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | Tribal Water Data [Map](https://gispublic.waterboards.ca.gov/portal/home/item.html?id=a71c1841907240e1a4d896c8cf2302a8) & [User Manual](https://cawaterboarddatacenter.github.io/tribal-water-data-map-manual/) |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Lindsey Metz](https://caseagrant.ucsd.edu/profiles/lindsey-metz)\*                                 | California Sea Grant Fellow | 2022      |                                                                                                                                                                                                                 |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Gabriella Moran](https://civicspark.civicwell.org/2021-22-fellows/entry/8611/)                     | CivicSpark Fellow           | 2021-2022 | Tribal Data Initiatives                                                                                                                                                                                         |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | [Tribal Water Data Initiatives Webpage](https://www.waterboards.ca.gov/resources/oima/tribal_water_data_initiatives/)                                                                                           |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Brook Thompson](https://www.brookmthompson.com/)                                                   | Stanford Fellow             | 2021      | Tribal Data Initiatives                                                                                                                                                                                         |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Corey Clatterbuck](https://caseagrant.ucsd.edu/profiles/corey-clatterbuck-sheherhers)\*            | California Sea Grant Fellow | 2021      | Healthy Watersheds                                                                                                                                                                                              |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | Trash                                                                                                                                                                                                           |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | [Trash Data Dive 2021](https://cawaterboarddatacenter.github.io/trash-data-dive-2021/)                                                                                                                          |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Ross Cooper](https://caseagrant.ucsd.edu/profiles/ross-cooper)                                     | California Sea Grant Fellow | 2020      | Trash Datathon                                                                                                                                                                                                  |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | Bioaccumulation                                                                                                                                                                                                 |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | CASG Article: [The Predicament of Subsistence Fishing and Seafood Contaminants](https://caseagrant.ucsd.edu/news/the-predicament-of-subsistence-fishing-and-seafood-contaminants)                               |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Maraid Jimenez](https://civicspark.civicwell.org/2020-21-fellows/entry/7745/)                      | CivicSpark Fellow           | 2020-2021 | Tribal Data Initiatives                                                                                                                                                                                         |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Anna Holder](https://caseagrant.ucsd.edu/news/2019-california-sea-grant-state-fellows-announced)\* | California Sea Grant Fellow | 2019      | Healthy Watersheds                                                                                                                                                                                              |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | Open Data & Science                                                                                                                                                                                             |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | Trash                                                                                                                                                                                                           |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | [CA Water Data Science Symposium](https://www.waterboards.ca.gov/resources/data_databases/wq_science_symposium.html)                                                                                            |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | [College of Water Informatics](https://www.waterboards.ca.gov/resources/oima/cowi/)                                                                                                                             |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | CASG Article: [Lean into Your Professional Swerves](https://caseagrant.ucsd.edu/news/lean-in-to-your-professional-swerves)                                                                                      |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [Nicole Hack](https://caseagrant.ucsd.edu/news/2018-california-sea-grant-state-fellows-announced)   | California Sea Grant Fellow | 2018      | Trash                                                                                                                                                                                                           |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | [Trash Data Dive](https://sites.google.com/sfei.org/trash/notes-from-the-field/data-dive?authuser=0)                                                                                                            |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | CASG Article: [Being a Datahead](https://caseagrant.ucsd.edu/news/nicole-hack-being-a-datahead)                                                                                                                 |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Andrew Hill\*                                                                                       | California Sea Grant Fellow | 2017      | Trash                                                                                                                                                                                                           |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | [Trash Tracker](https://github.com/CAWaterBoardDataCenter/Trash-Tracker)                                                                                                                                        |
|                                                                                                     |                             |           |                                                                                                                                                                                                                 |
|                                                                                                     |                             |           | CASG Article: [Tracking Trash](https://caseagrant.ucsd.edu/news/andrew-hill-tracking-trash)                                                                                                                     |
+-----------------------------------------------------------------------------------------------------+-----------------------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: \*Fellows who were then hired by the Water Boards
