# Professional Development

We are very supportive of individual and team professional development opportunities. Below are a couple of resources SWAMP Team members can tap into to advance their professional skills.

## Individual Development Plan (IDP)

Staff can complete an [IDP Form](https://www.documents.dgs.ca.gov/dgs/fmc/pdf/std637.pdf) annually to articulate their performance objectives for the coming year as well as their plans for achieving those objectives. Once drafted, staff review the document with their supervisor, revise as appropriate, and submit. Completing the form can help prioritize which trainings and other opportunities the individual might request to attend in the coming year.

## Training

Training Request Forms are required for all trainings, even Water Boards Academy trainings and required workplace trainings because they provide documentation needed in case of audits. See the [Training Section](https://cawaterboarddatacenter.github.io/swamp-manual/training.html) of this Manual for more details.

## Conferences

Attending conferences can help staff practice and develop their public speaking skills as well as provide opportunities to network and find and develop new partnerships (or nurture existing ones!). Being able to attend conferences requires lots of planning and paperwork, so it's a great idea to think about which conference(s) you might request to attend during your IDP process, and be ready to submit all of the required paperwork well in advance. See the [Training Section](https://cawaterboarddatacenter.github.io/swamp-manual/training.html) of this Manual for more details.

See the table below for a list of conferences that may be of interest and usually have intersection with SWAMP and broader OIMA priorities.

+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| Conference Name                                                                                                           | Time Frame | Frequency    |
+===========================================================================================================================+============+==============+
| [Earth Science Information Partners](https://www.esipfed.org/meetings) (ESIP)                                             | Jan        | Twice a year |
|                                                                                                                           |            |              |
|                                                                                                                           | Jul        |              |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [American Society of Limnology and Oceanography](https://www.aslo.org/meetings/) (ASLO)                                   | Feb/Mar    | Twice a year |
|                                                                                                                           |            |              |
| (Includes the Ocean Sciences Meeting & Aquatic Sciences Meeting)                                                          | May/Jun    |              |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [Women in Data Science](https://www.widsconference.org/conference.html) (WiDS)                                            | Mar        | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [Salmonid Restoration Federation](https://www.calsalmon.org/conferences) (SRF)                                            | Mar/Apr    | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [Code for America Summit](https://summit.codeforamerica.org/)                                                             | Mar-May    | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [National Water Quality Monitoring Council](https://www.epa.gov/awma/national-water-quality-monitoring-council) (NWQMC)   | Apr        | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [Society for Freshwater Science](https://freshwater-science.org/events) (SFS)                                             | May/Jun    | Annual       |
|                                                                                                                           |            |              |
| Also check out the [California Chapter](https://freshwater-science.org/my-sfs/chapters/california) (CalSFS)               |            |              |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [California Data Collaborative Water Data Summit](https://www.cawaterdatasummit.org/)                                     | Aug/Sep    | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [California Lake Management Society](https://www.california-lakes.org/calms-conference) (CALMS)                           | Oct        | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [Society for Open, Reliable, and Transparent Ecology and Evolutionary Biology](https://www.sortee.org/upcoming/) (SORTEE) | Oct        | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [Tribal EPA & U.S. EPA Region 9 Annual Conference](https://tribalepa.com/)                                                | Oct        | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [North American Lake Management Society](https://www.nalms.org/nalms-symposia/) (NALMS)                                   | Nov        | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [Society of Environmental Toxicology and Chemistry](https://www.setac.org/page/MeetingsandEvents) (SETAC)                 | Nov        | Annual       |
|                                                                                                                           |            |              |
| Also check out [Northern California Regional Chapter](https://www.norcalsetac.com/events.html) (NorCal SETAC)             |            |              |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [​American Geophysical Union](https://www.agu.org/Plan-for-a-Meeting/AGUMeetings) (AGU)                                    | Dec        | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [​American Fisheries Society](https://fisheries.org/events/) (AFS)                                                         | Variable   | Annual       |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
| [National Forum on Contaminants in Fish](https://www.epa.gov/fish-tech/national-forum-contaminants-fish) (Fish Forum)     | Variable   | Variable     |
+---------------------------------------------------------------------------------------------------------------------------+------------+--------------+
