# SWAMP Life Cycle

All SWAMP activities align with some component of the [data life cycle](https://www.waterboards.ca.gov/resources/oima/cowi/data_management_handbook.html), which consists of the seven phases outlined below. Here, we provide resources the SWAMP Team uses to effectively implement each phase.

## Plan and Prepare

The SWAMP Team, and all of the individuals within it, tend to have a number of co-occurring projects that are meant to help us advance and ultimately achieve our Mission. Managing multiple projects at once, given our limited resources -- time, funding, capacity (i.e. on person can only do so much in a day!) can be challenging -- so we like to make time to review all of our projects and prioritize them. This helps us focus our efforts and resources so that we can continue to make progress while also maintaing balance and preventing staff burnout.  

There are a couple of different strategic planning moments that occur: 

-   **SWAMP Strategic Planning**: Every three years or so, the SWAMP Team reviews and updates the SWAMP Strategic Plan to account for changes in priorities and bandwidth.

-   **Program Work Plans**: Every three years or so, SWAMP Program leads review and update their Program's Work Plans to account for changes in priorities and bandwidth.

-   **Individual Work Plans**: In December/January of each year, we recommend taking time to update individual work plans to account for changes in priorities and bandwidth. This is also a good time to review and update [Individual Development Plans](https://cawaterboarddatacenter.github.io/swamp-manual/development.html#individual-development-plan-idp), if staff have them!  

## Collect and Process

For SWAMP Statewide Monitoring Programs, data collection and processing generally occurs sometime between March and October each year. This timeframe can vary for each Statewide Monitoring Program so it's best to review each Program's Quality Assurance Project Plan (QAPP) for specific sampling and processing timelines.

The SWAMP Team does so much more than manage and coordinate SWAMP Statewide Monitoring Programs! For those projects, data collection and processing can look very different. Usually it comes in the form of engagement with internal and external partners, listening to the needs of communities that can most benefit from SWAMP data, information, and products, and figuring out how to operationalize and evolve our products and systems to better serve those communities and our partners. This process tends to be ongoing, although there may also be focused and concentrated periods where this listening and learning occurs.

## Assure and Analyze

For SWAMP Statewide Monitoring Programs, data analysis and quality assurance and quality control (QAQC) procedures are coordinated by SWAMP IQ, and specific components of the QAQC process can be found on the SWAMP IQ website or in each Program's QAPP.

For SWAMP Projects that are separate from statewide monitoring efforts, we work with our partners to test, "ground truth", and explore the effeacicy of our products and services. This can be separate from or simultaneous to the engagement and learning described in the "Collect and Process" step above. Similarly, this process tends to be ongoing, although there may also be focused and concentrated periods where this listening and learning occurs.

## Preserve and Store

Currently, data and information generated by SWAMP are stored in a number of different places. The SWAMP Team is working on developing a standard and consistent data and document retention system. Until then, the information below is meant to help increase transparency on where things are currently stored.

::: callout-note
Many of the links below require special access or for the user to be securely connected to the Water Boards network (via VPN or Remote Desktop)
:::

***Microsoft SharePoint & OneDrive*** 

-   Online storage site used for documents that will be shared and edited with people internal to Water Boards -- avoids version control issues

-   [SWAMP SharePoint](https://cawaterboards.sharepoint.com/sites/OIMA/SWAMP/SitePages/Home.aspx), [SWAMP IQ SharePoint](https://cawaterboards.sharepoint.com/sites/OIMA/SWAMP-IQ/SitePages/Home.aspx), [OIMA SharePoint](https://cawaterboards.sharepoint.com/sites/OIMA/SitePages/Home.aspx)

***Network Drives***

-   SWAMP: S:\\OIMA\\SHARED

-   SWAMP IQ: S:\\OIMA\\SHARED\\QA&DM

    -   Used to store core, static materials dated back to SWAMP IQ's start in 2014.

    -   Archive for old documents and storage for documents we want backed up. 

***Google Drive***

-   Online storage site used for documents that will be posted to the SWAMP and SWAMP IQ Wiki pages

-   Shared and edited with people external to Water Boards

***FTP Site***

-   The [SWAMP FTP Site](https://ftp.waterboards.ca.gov/WebInterface/login.html#/) is used to share large files and to submit field data through data entry shell databases

-   Request the username and password from [OIMA-helpdesk\@waterboards.ca.gov](mailto:OIMA-helpdesk@waterboards.ca.gov)

## Publish and Share

### SWAMP Data

After SWAMP Data are assessed and processed by SWAMP IQ, they are published and stored in the [California Environmental Data Exchange Network](http://ceden.org/index.shtml) (CEDEN), which is also pushed to and available on the [California Open Data Portal](https://data.ca.gov/dataset/surface-water-aquatic-organism-tissue-sample-results).

### SWAMP Information & Products

[***Water Boards Website***](https://www.waterboards.ca.gov/water_issues/programs/swamp/)***:*** our main way of sharing information and products to the public

[***SWAMP Wiki***](https://sites.google.com/site/swampwikihomepage/): what we use to share information with our external contractors and collaborators

[***SWAMP Data Dashboard***](https://gispublic.waterboards.ca.gov/swamp-data/): the primary SWAMP data visualization tool

[***GitHub***](https://github.com/CAWaterBoardDataCenter): used to develop and share select SWAMP products (like this Manual!)

### SWAMP Meetings & Events

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| Meeting or Event                                                                                                                                                                | Frequency                                                                                                            | Audience                                                                                         |
+=================================================================================================================================================================================+======================================================================================================================+==================================================================================================+
| [SWAMP Roundtable](https://sites.google.com/site/swampwikihomepage/roundtable-meetings?authuser=0)                                                                              | Quarterly                                                                                                            | Internal SWAMP Regional and Statewide Program Coordinators, external contractors, invited guests |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| California Aquatic Bioassessment Workgroup                                                                                                                                      | [Quarterly Meetings](https://sites.google.com/site/swampwikihomepage/bioassessment?authuser=0)                       | Quarterly meetings: Bioassessement partners                                                      |
|                                                                                                                                                                                 |                                                                                                                      |                                                                                                  |
| (part of the [Statewide Bioassessment Monitoring Program](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioassessment/))                                           | [Annual Meeting](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioassessment/training.html#cabw) (CABW) | Annual meeting: Open to the public                                                               |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| [Safe to Eat Workgroup (STEW)](https://mywaterquality.ca.gov/monitoring_council/bioaccumulation_oversight_group/index.html)                                                     | Quarterly                                                                                                            | Open to the public                                                                               |
|                                                                                                                                                                                 |                                                                                                                      |                                                                                                  |
| (part of the [Statewide Bioaccumulation Monitoring Program](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioaccumulation_monitoring.html))                        |                                                                                                                      |                                                                                                  |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+
| [California Cyanobacteria and Harmful Algal Bloom (CCHAB) Network](https://mywaterquality.ca.gov/monitoring_council/cyanohab_network/index.html)                                | Quarterly                                                                                                            | Open to the public                                                                               |
|                                                                                                                                                                                 |                                                                                                                      |                                                                                                  |
| (part of the [Statewide Freshwater and Estuarine Harmful Algal Bloom (FHAB) Program](https://www.waterboards.ca.gov/water_issues/programs/swamp/freshwater_cyanobacteria.html)) |                                                                                                                      |                                                                                                  |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+

## Discover and Integrate

As we discover new things and/or opportunities to improve the data, products, or services we generate, we integrate them into the project or process. Sometimes this can occur quickly, other times we make note and incorporate things into the next strategic planning opportunity. See the [Plan and Prepare](https://cawaterboarddatacenter.github.io/swamp-manual/lifecycle.html#plan-and-prepare) section above for more details.

## Describe

For SWAMP Statewide Monitoring Programs, data are described through metadata and data dictionaries that are available on the SWAMP IQ website, via the database where data are downloaded (e.g. CEDEN, CA Open Data Portal).

For SWAMP Projects that are separate from statewide monitoring efforts, information and context about the project can be found in specific project documentation.

The SWAMP Team is also using this Manual to document the more nuanced parts of how we do what we do so that it's easier for folks to find what they need to do their work.
