# Offboarding

You're moving on and up -- here's what you need to know & do before we wish you a fond farewell.

## Process

If you are a term team member or leaving voluntarily, initiate a conversation with your supervisor about your departure via a Teams meeting or phone call. Your supervisor will initiate your offboarding paperwork and work with our personnel specialist (currently Alicyn Chappelle) to make your departure smooth. Your departure may be called a separation (leaving state service or, for IT's purposes *only*, transitioning to another California state agency), transfer (to another California state agency), or retirement (retiring from the Water Boards) depending on your specific situation.

Two [offboarding checklists](https://waternet.waterboards.ca.gov/das/benefits/employee_change.shtml) are available on Waternet (VPN login required): [Separation Checklist](https://waternet.waterboards.ca.gov/das/forms/show_form.php?rec_id=307) and [IT Employee Separation Procedures](https://waternet.waterboards.ca.gov/dit/help_desk/docs/IT-Employee-Separation-Proceedure.pdf). [Additional considerations](https://waternet.waterboards.ca.gov/training/docs/staffdev/transition_planning.pdf) are available for retiring employees. You may want to go through these with your supervisor as you offboard. You may be contacted about the items on either checklist by your supervisor, the accounting office, business services, the personnel office, or DIT. If you know items on the checklists are outstanding, consider being proactive about addressing them prior to your departure.

Your supervisor may also schedule an exit interview with you as you get closer to your separation date. The interview is informational and an opportunity to provide feedback to your supervisor and OIMA management. All team members should approach this interview using the same [values](https://cawaterboarddatacenter.github.io/swamp-manual/values.html) and [expectations](https://cawaterboarddatacenter.github.io/swamp-manual/expectations.html) outlined in this manual.

::: callout-important
If you are a state employee separating from the Water Boards but remaining in state service, it may be advantageous for you to start at your new agency the day immediately following your separation date from the Water Boards to avoid a break in service. Discuss your situation with the personnel specialist and future employer to ensure an easy transition.
:::

More SWAMP-specific offboarding information will be added here by the SWAMP team.

## Equipment

The [offboarding checklists](https://waternet.waterboards.ca.gov/das/benefits/employee_change.shtml) (VPN login required) detail the return of any IT equipment, IDs, badges, etc. One of these forms should be completed at least 5 business days prior to your departure.

## CalPERS

## General offboarding advice

Leaving your position in SWAMP may evoke an array of emotions, and you may have a number of people that you want to say farewell to. We suggest thinking about how you might want to be celebrated within SWAMP/OIMA and sharing this information with your supervisor or a trusted colleague (after informing them of your expected departure). You may want to consider sharing the work, growth, and collaborations you are most proud of in addition to your appreciation for your colleagues. Being forthright can help you and your co-workers manage your transition so you can have a positive departure from SWAMP.
