# Onboarding

Here is a non-comprehensive, but hopefully informative guide to onboarding to the SWAMP Unit. The majority of this information in this section is aimed towards starting at SWAMP as a rank-and-file (non-supervisory) state employee. Please re-reference this page throughout your time at SWAMP!

## Initial Logistics

In your first week, your supervisor will help you:

-   Get access to your Water Boards email
-   Get any equipment or supplies you need (e.g. laptop, office supplies)
-   Get a badge to enter the CalEPA building (as appropriate)
-   Review & sign paperwork
    -   **Fellows & Interns** will need to have the following compiled & signed
        -   Project Description (the one submitted with the original host application)
        -   STD 689-Oath of Allegiance
        -   Emergency Notification Request form
        -   Internet/Intranet Policy Certificate
        -   Welcome Letter
        -   Letter of Agreement
        -   Duty Statement
-   Forward relevant meeting invitations and other information to you, such as:
    -   SWAMP Unit Meetings
    -   SWAMP Roundtable Meetings
    -   Optional SWAMPside coworking Meetings
    -   OIMA All-Staff Meetings
    -   Other meetings that will be relevant to your work
-   Get added to relevant email lists, such as:
    -   SWAMP Roundtable email list
    -   OIMA All-Staff email list
-   Get added to relevant Microsoft Teams Channels & Group Chats, such as:
    -   OIMA Data Team
    -   Water Boards Data Community Team
    -   SWAMP Unit Chat

We recommend you take some time to:

-   Go through this manual and familiarize yourself with SWAMP, OIMA, and the Water Boards
    -   For **Fellows & Interns**, the rest of this Onboarding section may not apply to you (e.g. HR Forms, etc.) - your supervisor can provide guidance on what is relevant to you.
-   Install any software you will need (see the [Tech Access, Setup, & Support Section](https://cawaterboarddatacenter.github.io/swamp-manual/tech.html) for guidance)
    -   If you will need to install a lot of different programs, we recommend working with DIT to bulk install programs. Programs that are commonly used in SWAMP that benefit from bulk installation by DIT include:
        -   ArcGIS Pro, PowerBI, Tableau (folks usually prefer and install one over the others)
        -   R & RStudio
        -   Git
        -   Zoom
-   Familiarize yourself with Microsoft Teams, Outlook, any other software you may use (see the [Communication Section](https://cawaterboarddatacenter.github.io/swamp-manual/expectations.html#communication) for communication norms, resources, and expectations)
-   Review the [New Employee Orientation Resources](https://waternet.waterboards.ca.gov/das/benefits/emp_orientation.shtml) & make a note of [state holidays](https://www.calhr.ca.gov/employees/pages/state-holidays.aspx) on your calendar
-   Add any known / already approved time off to your calendar (see the [Work Schedule Section](https://cawaterboarddatacenter.github.io/swamp-manual/expectations.html#work-schedule) for guidance)
-   Familiarize yourself with resources related to the project(s) you will be working on
-   Meet others in SWAMP/OIMA and others that you'll work with on your project(s)
-   Take any mandatory training (e.g. IT Security, Field Safety)
-   Review optional training available through the Training Academy and sign up for courses of interest. (See the [Training Section](https://cawaterboarddatacenter.github.io/swamp-manual/training.html) for more guidance)
-   ASK QUESTIONS! You'll probably have a lot of questions as you settle in - please don't hesitate to ask your supervisor and/or team members as they come up!

## HR forms

On your starting day, you will receive a package of forms and documents from the HR department including your duty statement, tax forms, direct deposit forms, questionaires (diversity, military), CalPERS forms, leave forms, and medical insurance forms

You will also be asked to submit a photocopy of either your passport or a combination of your driver's license and social security card to the HR representative (currently Alicyn Chappelle). All forms apart from the medical insurance forms must be submitted within the first couple of days. Medical insurance forms must be submitted within the first 60 days for you to qualify for enrollment; however, the sooner you submit these forms the sooner you will have health coverage.

## Bargaining units

Each classification within the SWAMP unit is associated with a bargaining unit. The bargaining units, with the State, determine many of the benefits & guidelines described here. For that reason, you should read the latest contract or Memorandum of Understanding (MOU) for your bargaining unit to determine benefits as applicable for you. Additional benefits specific to your bargaining unit may exist for you based on the MOU that are not described in this manual. Finally, supervisory positions may have varying benefits beyond those listed in this manual.

| SWAMP Position Classification                     | Bargaining Unit | CBID |
|---------------------------------------------------|-----------------|------|
| Scientific Aid                                    | 11              | R11  |
| Environmental Scientist (incl. Senior Specialist) | 10              | R10  |
| AGPA                                              | 1               | R01  |
| Senior Environmental Scientist - Supervisory      | 10              | S10  |

## Leave types

When onboarded, employees in most classifications will be able to select a leave type: **annual leave** vs. **vacation/sick leave**. Comparisons of leave accrual and use between leave types are available in [this chart](https://www.calhr.ca.gov/employees/Pages/vacation-vs-annual-leave-comparison-chart.aspx).

Important FAQ for leave types:

-   You are only allowed to switch leave types every 2 years. Check with our HR liaison about switching leave types.

-   Leave types are also connected to different types of non-work-related disability leave, which may impact your income should you need to go on disability leave. Non-work-related disability leave types are compared for Unit 10 employees on this [flyer](https://capsscientists.org/wp-content/uploads/2018/02/Facts-about-ENDI.pdf). More information about non-work-related disability leave is also available on the EDD [website](https://edd.ca.gov/).

-   Leave accrual can be impacted by the number of days/hours you work in a month.

**Need additional leave?**

Under the [Voluntary Personal Leave Program](https://hrmanual.calhr.ca.gov/Home/ManualItem/1/2114), you can exchange a percentage of your salary to accrue additional leave hours per month. See the link above for more information, and contact our personnel specialist for more details.

## CalPERS

CalPERS is the [California Public Employees Retirement System](https://www.calpers.ca.gov/), which you will be enrolled in as a new employee. It provides benefits including medical coverage (health, dental, and vision insurance) and retirement for employees of the state of California.

### Medical coverage

You should select health insurance by submitting the appropriate forms within 60 days of starting with the State. If you select health insurance, you will pay the difference between what the state provides for healthcare (a base amount monthly) and the monthly cost for your selected health insurance. This amount is removed from your monthly paycheck. Employees may elect to receive cash in lieu of their state-sponsored medical insurance and/or dental insurance plan through the [FlexElect](https://www.calhr.ca.gov/state-hr-professionals/Pages/benefits-administration-manual-flexelect.aspx) program. You must certify you have qualifying group health and/or dental insurance through a spouse, domestic partner, or other source. FlexElect cash is distributed monthly.

You can make changes to your health, dental, and vision insurance selections two ways:

1.  Annually during open enrollment, which occurs in the fall of each year. Your new insurance selections begin the following January.
2.  After a [qualifying event](https://www.insurance.ca.gov/01-consumers/110-health/30-have/qual-life-events.cfm) in your life.

To learn more about the health coverage available to you, please visit the CalPERS website as well as the website for your [bargaining unit](https://cawaterboarddatacenter.github.io/swamp-manual/onboarding.html#bargaining-units) to learn about costs specific to you. We include some helpful links below:

-   [CalPERS Health Program Guide](https://www.calpers.ca.gov/docs/forms-publications/health-program-guide.pdf) (pdf) -- broad overview of the health program

-   [CalPERS 2023 Health Benefits Summary](https://www.calpers.ca.gov/docs/forms-publications/2023-health-benefit-summary.pdf) (pdf) -- description of different health plans and their statewide availability

-   [CalPERS 2023 Plans & Rates](https://www.calpers.ca.gov/page/active-members/health-benefits/plans-and-rates) (web link)

### Retirement benefits

Learn more about your CalPERS retirement benefits on their [website](https://www.calpers.ca.gov/page/life-events/retirement), which includes retirement planning checklists, calculators, classes, and explanations of benefits.

## Timesheets & Pay

Staff should complete and submit their timesheets by the 25th of each month. Direct deposit typically hits the last day of the pay period (end of the month), potentially earlier if you use a credit union.

It typically takes \~1 month for new staff to be entered in the electronic timesheet system (BizFlow), so the first timesheet is done by filling out an excel template.

### Bizflow: Timesheets

**Logging in**: To [login](https://ework.waterboards.ca.gov/bizflow/index.jsp?v=_5FtHCSz6JfUxrK7) you must use MS Edge browser and be connected to VPN (or on the network at CalEPA building). Use your workstation username (waterboards email address) and password to login.

**eTimesheets**: From the menu, -- click the eTimesheet tab --\> eTimesheet Process --\> Current eTimesheet to begin. Select the pay period (month) to load a timesheet. All work hours must be associated with a Task ID -- your supervisor will provide this, and it will be saved on all future timesheets. Work hours go on page 1, leave hours go on page 2. Use the \> and \< symbols on the timesheet to navigate between pages. Make sure your total hours fit the expected hours at the bottom of the timesheet, both monthly and daily, unless otherwise directed by your supervisor. Once complete, sign the 1st page of the timesheet, change status in the upper left corner to "Submit to Supervisor", and click the green check box to complete the process.

**BizFlow Tips**

-   For first-time users and info on how to change your settings, see [Instructions on how to use BizFlow](https://waternet.waterboards.ca.gov/das/human_resources/docs/BizFlow_Gen_Instructions_15Jul2022.pdf) (intranet site; requires VPN login)
-   [Check out the FAQs](https://waternet.waterboards.ca.gov/das/human_resources/docs/BizFlow_FAQs.pdf)

### Electronic Paystubs

You can view and download your paystubs from the [Cal Employee Connect portal](https://connect.sco.ca.gov/). Your supervisor will request login information for you from HR (personnel specialist) after your first paycheck.

::: callout-tip
Leave balances are included on your paystubs and can be tracked in Cal Employee Connect, but they are always a month (or more) behind. You may want to track them in real-time in your own spreadsheet.
:::

## Office-centered and Remote-centered Work

The [Telework Policy](https://waternet.waterboards.ca.gov/das/human_resources/docs/CalEPA-and-BDO-telework-policy.pdf) for CalEPA and the Water Boards allows remote-centered work options for all staff as long as business needs can be met.

All staff are required to fill out a Work Week Agreement and Telework Agreement that specifies where you will typically work on a given day of the week (office or remote) and your typical work hours. All employees (including Student Assistants, Retired Annuitants, Supervisors and Managers) are required to complete both agreements, regardless of their telework or work week status.

Your Work Week Agreement and Telework Agreement need to be created in BizFlow within 2 months of starting work. All Telework Agreements and Work Week Agreements must be reviewed and updated on an annual basis each calendar year in January.

As of January 2023, OIMA still maintains enough office space that staff will be assigned a cubicle or personal workstation in the CalEPA building whether or not they primarily work remotely.

### Work Week Agreements 

Below are the approved work schedules.

-   **Regular/Standard or Fixed Work Schedules** - In accordance with Government Code 19851 a regular work schedule is defined as five (5) days a week, eight (8) hours a day and not more than 40 hours a week. If you are on a regular work schedule, please complete the agreement with a work schedule that reflects this.

-   **Alternate Work Schedules (AWS)** have been released, therefore, please review the applicable AWS before recertifying your AWS agreement. Please note, your AWS agreement must match the CalHR AWS otherwise it will be rejected. Also see: [Calendars for Alternate Work Week Schedules](https://www.calhr.ca.gov/Pages/publications-awws-calendars.aspx)

-   **Flex Schedule**, in accordance with CalHR policy, Flex Schedule is defined as "An arrangement that permits employees to flex or adjust their start and end times, so long as the employee has worked his/her scheduled number of hours per day." Therefore, you must have either an Alternate Work Schedule or a Regular Work schedule regardless of whether you have a Flex Schedule. At no time may a Flex Schedule result in overtime hours worked.

-   **Exempt employees** on other than a Regular/Standard or Fixed Work schedule (e.g., AWS, Flex time), please refer to the [CalHR Human Resources Manual](https://hrmanual.calhr.ca.gov/Home/ManualItem/1/1501).

### Telework Agreement

Make sure you review all sections of the Telework Agreement prior to submitting it (e.g., alternate work location, telework day(s), etc.).

If you are NOT teleworking or not eligible to telework, you still need to perform an annual review of your agreement and recertify that you are not teleworking.

### Bizflow Process

1.  Log in to Bizflow:
2.  Select "Self-Service" then "Work Items" and "Employee Self-Service Work List"
3.  Select the Agreement by clicking on the word "Review" (blue link)
4.  Your form will contain information from the previous year. Make any necessary changes.
5.  Check all the acknowledgment boxes on both forms.
6.  Select the appropriate approvers. If you are unsure who your approvers are, please check with your Supervisor.
7.  From the drop-down menu at the top left, choose "Submit Request" then click the green check box button.

For more information, visit the [Telework Program Page](https://waternet.waterboards.ca.gov/das/human_resources/telework.shtml).

## Equipment

All staff are assigned a laptop (typically Dell or HP) that they can use at home and the office. The Water Boards only uses PCs and does not generally support any Mac-based hardware. Office workstations are set up with two wide screen monitors, keyboard, mouse and docking station where you plug in your laptop.

If you find you need different or additional equipment at your office or home desk (e.g., to make your workspace more ergonomic with a wireless keyboard or mouse), please speak to your supervisor who can work with you and IT to make the appropriate requests. Ergonomic equipment may be made available through a [Reasonable Accommodation Request](https://waternet.waterboards.ca.gov/eeo/reasonable/index.shtml) (intranet link requires VPN login). Work with your supervisor for guidance on preparing the request.

Equipment available to take home includes: laptop, laptop bag, standard monitor, keyboard, mouse, headset, adjustable monitor stand, adjustable tilting laptop stand. To request additional equipment or to report issues with any of your equipment, send an email to the [IT Help Desk](mailto:help@waterboards.ca.gov). This will log a ticket in their tracking system and they will respond typically the same day.
