# Tech Access, Setup, & Support

Phew!

## Need equipment?

## Remote desktop vs. VPN

## Accessing & downloading software

-   ESRI Services (ArcGIS Pro/ArcGIS Portal) 

    -   **ArcGIS Pro** is the main desktop GIS application available to Water Boards staff. ArcGIS Pro can be downloaded from the Software Center. If you do not see ArcGIS Pro in the Software Center, contact the Help Desk at [help\@waterboards.ca.gov](mailto:help@waterboards.ca.gov) so that they can add it your list of available applications. Future releases of ArcGIS Pro and other ESRI applications should be automatically added to the Software Center as they are approved by DIT. You can use the Software Center to update your installation. 

    -   The **Water Boards ArcGIS Portal** (<https://gispublic.waterboards.ca.gov/portal/>) is an online platform for publishing and sharing ESRI-produced GIS resources with others at the Water Boards. These resources can also be shared with people outside of the Water Boards (with approval). For those familiar with ArcGIS Online, ArcGIS Portal is the enterprise version of ArcGIS Online. With ArcGIS Portal, you can: 

        -   Create and share maps, story maps, and other applications 

        -   Search for GIS content within the Water Boards 

        -   Create groups to share GIS information with colleagues 

        -   Download maps, layers, and GIS data for use in ArcGIS Pro and other applications 

        To activate your Water Boards ArcGIS Portal membership (required for viewing, downloading, and publishing resources on the portal), email the DIT GIS Unit at [gis\@waterboards.ca.gov](mailto:gis@waterboards.ca.gov).  

        To log into Portal, use the same username and password that you use for your state-issued laptop or computer. 

        -   Username: The default format is "\[your work PC login\]\@EPA" (e.g. jsmith\@EPA) OR "epa\\\[your work PC login\]" (e.g. epa\\jsmith) 

        -   Password: \[your work PC password\] 

    -   Public sharing: Resources published on the ArcGIS Portal can be shared outside of the organization to the public (no Portal log-in required), but this requires approval from the DIT GIS Unit. See the Public Sharing Requirements on the GIS Unit wiki ([start \[gis\] (ca.gov)](http://wiki.waterboards.ca.gov/gis/doku.php#gis_portalswater_board_portal_and_state_geoportal)) and ensure that you complete each one of the steps before you submit a completed Public Publishing Form to the GIS Unit. The approval process can take some time, depending on how complex your project is and how busy the GIS Unit staff are, so plan ahead if you are working against a deadline. 

    -   For more information about ArcGIS Pro and the Water Boards ArcGIS Portal, view the [GIS Unit wiki](http://wiki.waterboards.ca.gov/gis/doku.php).

## Community
