# SWAMP Culture {.unnumbered}

In SWAMP we understand that our culture is a result of our shared core values and our behaviors - and we take actions to support a culture that makes SWAMP a place we want to work.

> Culture is a set of living relationships working towards a shared goal. It's not something you are, it's something you do"

*The Culture Code, Daniel Coyle*

> A culture is strong when people work with each other, for each other. A culture is weak when people work against each other, for themselves.

*Simon Sinek*

# Our Values

The following four values are at the core of who we are and how we work as an office (OIMA) and within the SWAMP Unit at the Water Boards:

**We build trust:** we strive to be a trusted source of water data, information, and processes, and we invest the time and space required to build, rebuild, and maintain trusting relationships.

**We adapt:** we strive to be adaptable and innovative in how we work and the products, services, and resources we develop.

**We work in partnership:** collaboration and partnerships are key to who we are and how we work. We believe the way we work directly impacts what we produce.

**We drive quality:** we strive to produce quality information, data, products, and services. We know the quality of the systems and processes we use determine the outcomes we are able to achieve.

See the [OIMA Values Statement](https://www.waterboards.ca.gov/resources/oima/docs/oima-values-statement-2023.pdf) for how each of these values have been operationalized into behaviors that we are all empowered, expected, and held accountable to demonstrating.

# Our Why Statement

Our "Why" is the purpose, cause, or belief that drives OIMA's work. In 2025, OIMA came together to define our Why Statement as:

> "We are here to empower & support people, so that our water data systems educate communities & inform decisions to protect the environment and public health."

# Social Committee

OIMA has a social committee to plan fun stuff for staff throughout the year! Contact Tessa at tessa.fojut\@waterboards.ca.gov to learn more or become involved.

# Co-work Sessions

OIMA staff have fostered a culture of camaraderie, collaboration, and accountability through holding regular co-work sessions for various projects and purposes. Co-works are remote or in-person meetings in which colleagues come together to work either collaboratively or individually on projects to achieve specific tasks. These sessions provide opportunities to create some structure while doing remote work, set goals, and help each other accomplish those goals. Since people have come back to the office more frequently, we have been meeting up at different coffee shops every few weeks to get some in-person face-time with coworkers. If you're new to the OIMA team, a great way to become involved in projects, recruit collaborators, and get to know your colleagues is to join existing co-work session series or schedule your own co-work!
