# Training

As a Water Boards employee, you have access to training and training-related services to support your personal and professional development, all in support of the Water Boards' mission. Training Services is comprised of the *Training Academy* and *Training Office*, which offer different types of training and which you access differently.

***Water Board Training Academy***

-   Offers in-house virtual and in-person training courses
-   Staff self-register for courses via the Cornerstone Learning Management System - see the [Cornerstone Introductory Modules](https://cawaterboards.sharepoint.com/Training/SitePages/Cornerstone-Introductory-Modules.aspx) and/or the [Cornerstone Training Recording](https://cawaterboards.sharepoint.com/:v:/r/Training/Documents/Training%20Corner%20Newsletters/Cornerstone%20Training%20Video.mp4?csf=1&web=1&e=YtjuDO) to get started
    -   Note that Cornerstone accounts for new employees can be delayed, but are automatically created each night. It's recommended that new employees check daily to see if you are established and contract Training services if you experience a significant delay.
-   Works with staff to develop new classes

***Water Boards Training Office***

-   Gives ​​​​​​access to external events (training, conferences, PE/PG license preparation classes and higher education requests - essentially, anything *not* found in the Cornerstone system)
-   Processes for requesting to attend an external training event or conference differ - see the [Access External Training and Conferences SharePoint](https://cawaterboards.sharepoint.com/Training/SitePages/Access-External-Training-and-Conferences.aspx) for guidance and forms
-   **Never** pay for a class yourself, without explicit pre-approval from the Training Office (or you won't be eligible for reimbursement)

## Internal Training

Internal Training refers to in-house training courses supported by the *Water Board Training Academy.*

**How to sign up for Internal Water Board Training Academy Courses:**

-   Watch your inbox for course announcement emails or visit the [Training Services SharePoint](https://cawaterboards.sharepoint.com/Training/SitePages/Home.aspx)
-   Search Cornerstone (via your Miscrosoft Apps) for on-demand resources and upcoming training opportunities

**Approval Process:**

-   Get supervisor approval to take training(s)
-   Self-register on Cornerstone

**Attendance Reminder:**

To receive attendance credit, you must be present and participate for the entirety of the course or you will receive a [no-show](https://cawaterboards.sharepoint.com/Training/SitePages/Training-Services-Registration-Guidelines.aspx#training-services-no-show-guidelines "https://cawaterboards.sharepoint.com/Training/SitePages/Training-Services-Registration-Guidelines.aspx#training-services-no-show-guidelines"). Although we understand that emergencies arise during training, missing more than 15-minutes of any course will result in a no-show with no attendance credit given. This is a Training Services guideline that cannot be overruled by the instructor. To ensure proper attendance, rename your video box to list your first and last name. 

## External Training

External Training refers to external events (training, conferences, PE/PG license preparation classes and higher education requests) supported by the *Water Boards Training Office*.

**When is Training Office Approval Required?**

-   There is a registration/tuition cost
-   There are travel costs (hotel, car rental, per diem, etc.)
-   You want the event added to your training history 

**How to sign up for (non-Academy) External Training:**

-   Visit the [Training Services SharePoint](https://cawaterboards.sharepoint.com/Training/SitePages/Home.aspx) to:
    -   Review how to [Access External Training and Conferences](https://cawaterboards.sharepoint.com/Training/SitePages/Access-External-Training-and-Conferences.aspx)
    -   Download the current [Training Request Form](https://cawaterboards.sharepoint.com/Training/SitePages/Forms.aspx) (TRF)
-   Fill out the TRF and obtain supervisor approval (digital signature)​
-   Email signed TRF to your Training Liaison
-   Training Liaison submits TRF to Training Office for processing, by submission deadline
-   Training Office emails you the approved forms when registration is complete

**How to sign up for (non-Academy) Conferences:**

-   Be prepared to plan head when requesting to attend any Conference or External Training.
-   Visit the [Training Services SharePoint](https://cawaterboards.sharepoint.com/Training/SitePages/Home.aspx) to:
    -   Review how to [Access External Training and Conferences](https://cawaterboards.sharepoint.com/Training/SitePages/Access-External-Training-and-Conferences.aspx)
    -   Review the Fiscal Year's Conference submittal deadlines. The current submission deadline for Conferences is **35 business days prior to the registration deadline.**
    -   Download the current [TRF & In-State Travel Form](https://cawaterboards.sharepoint.com/Training/SitePages/Forms.aspx)
-   Fill out the TRF and In-State Travel Form and obtain supervisor approvals (digital signature)​
    -   Attach copy of registration form, event agenda, meal or session preferences (if applicable), etc.​
-   Email signed forms and attachments (if applicable) to your Training Liaison
-   Training Liaison submits them to Training Services for processing
-   Once your request is fully approved, Training Services will either process registration on your behalf and inform you of your approval or will send you authorization to self-register and seek reimbursement.

See the [Professional Development Section](https://cawaterboards.sharepoint.com/Training/Documents/conf_n_symp_list.pdf) for a list of conferences that may be of interest.

## Resources

-   [Water Board's Training Services Page (SharePoint)](https://cawaterboards.sharepoint.com/Training/SitePages/Home.aspx) 
-   [Training FAQ's](https://cawaterboards.sharepoint.com/Training/SitePages/FAQ.aspx) 
-   [Training Forms](https://cawaterboards.sharepoint.com/Training/SitePages/Forms.aspx) 
-   [Training Services Registration Guidelines](https://cawaterboards.sharepoint.com/Training/SitePages/Training-Services-Registration-Guidelines.aspx#training-services-registration-guidelines) (Visit if you're unsure of the training type you're wanting to attend)

## Recommended On-demand Training Resources:

-   Cornerstone on-demand resources
    -   Suggested Learning Search Topics:
        -   Data Science
        -   Tribal History
        -   Advancing Equity
-   [College of Water Informatics (CoWI) Data Tool Kit](https://www.waterboards.ca.gov/resources/oima/cowi/data_training.html) 
-   [Tribal Historical and Legal Foundations](https://waternet.waterboards.ca.gov/training/videos/tribal_training1.mp4)
-   [Tribal Cultural Resources](https://waternet.waterboards.ca.gov/training/videos/tribal_training2.mp4)
-   [Tribal Cultural Awareness and California Native American History](https://www.youtube.com/watch?v=PttFI1WvTTY)
-   [CA Water Quality Law 101](https://waternet.waterboards.ca.gov/wndata/videos/wq_law_101/wqlaw.mp4): foundational training in CA law including Porter Cologne Water Quality Control Act, Federal Clean Water Act, Basin Plans, etc.  

## **Contacts**

Training Liaison: Devan Burke

Backup Training Liaison: TBD

::: callout-note
Reminder to add backup when identified
:::
